### ISSUE TITLE
About the Pretrained Weights

### ISSUE THREAD

**Issue by nsl2014fm** [barisbatuhan/FaceDetector#1]
hi~Thans for your wonderful work
Do you have any plan to release the pretrained weights models?

**Comment by barisbatuhan** [comment]
Hi @nsl2014fm, 

Our pre-trained weights are already shared on the readme page. Here is the link: https://drive.google.com/drive/u/1/folders/11Kxzz4EnorI6uA6HK9x-UH_5BrQyXlBW

If you are interested in detection in comics & drawings, I have a new project that will be released soon. Please follow me for future updates. Thanks for your interest :)
